### PR TITLE
Display cluster resource usage on node list

### PR DESCRIPTION
**Pull request by BennieMeng**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>

> /kind feature

**What this PR does / why we need it**:
show cluster resource usage on node list
image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/Qihoo360/wayne/issues/140

### CODE REVIEW

**Comment by chengyumeng** [comment]
Node 使用概况可以也用图展示吧？为什么用一个看起来没做好的列表？ @BennieMeng @wilhelmguo

**Comment by wilhelmguo** [comment]
@BennieMeng 目前整体是什么效果

**Comment by BennieMeng** [comment]
@wilhelmguo 上边给了个图啊

**Comment by wilhelmguo** [comment]
> @wilhelmguo 上边给了个图啊

全屏效果

**Pull request merged**
